# Generated by Django 5.0.7 on 2024-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_preview_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку",
                max_length=100,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
